name: JaggedHorizonPhoto
favicon: null
layout_spectrum: 0.6032785074785352
typography_spectrum: 0.8348647588863969
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#9D2D3C'
    - '#DDE4DD'
    - '#BCAB47'
    - '#6B574B'
    - '#160600'
  brandStrength: 0.4576519418042153
  lightness: 0.7177693890407681
  saturation: 0.7228053845465183
  rhythmicContrast: 0.8071998748928308
purpose: []
